#!/usr/bin/env python2.7
'Perform various inference and data management tasks using SMC++'
import argparse

import psmcpp.lib.commands as commands

def init_parser_class(parser_module, parser):
    def main(args):
        parser_module.main(args)
    parser.set_defaults(func=parser_module.init_parser)

def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers("Available commands")

    # Initialize arguments. Each object is responsible for setting the
    # args.func, where the work takes place.
    estimate_p = subparsers.add_parser('estimate', help='Fit SMC++ to data')
    init_parser_class(commands.estimate, estimate_p)
    decode_p = subparser.add_parser('decode', help='Perform posterior decoding')
    init_parser_class(commands.decode, decode_p)
    convert_p = subparser.add_parser('convert', help='Convert VCF to SMC++ input format')
    init_parser_class(commands.convert, convert_p)
    plot_p = subparser.add_parser('plot', help='Plot estimated size histories')
    init_parser_class(commands.plot, plot_p)

    # Go.
    args = parser.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
